# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'Morantron/tmux-fingers'

# Default shell
set -g default-shell /usr/bin/zsh

# Kanagawa Colors
set -g @white "#dcd7ba"        # fujiWhite
set -g @gray "#2a2a37"         # sumiInk4
set -g @dark_gray "#1a1a22"    # sumiInk2
set -g @light_purple "#363646" # sumiInk5
set -g @dark_purple "#54546D"  # sumiInk6
set -g @cyan "#6a9589"         # wave aqua
set -g @green "#938aa9"        # springViolet1
set -g @orange "#dca561"       # autumn orange
set -g @red "#e46876"          # wave red
set -g @pink "#d27e99"         # sakura pink
set -g @yellow "#ff9e3b"       # roninYellow

set -g status-style "fg=#{@red},bg=default"
set -g status-left "[#{session_name}]"
set -g status-right '#{user}@#H: #{=|-40|…;s|^#{HOME}|~|:pane_current_path}'
set -g window-status-format  "#[fg=#{@cyan},bg=default] #{window_index}:#{window_name} #[default]"
set -g window-status-current-format "#[fg=#{@white},bg=default,bold] #{window_index}:#{window_name} #[default]"
set -g window-status-separator " #[fg=#{@cyan}]|#[default] "
set -g pane-border-format "#{?pane_active,#[bold]#[fg=#{@white}],#[default]} [ #{pane_index}:#{pane_current_command} ] "
set -g pane-border-style "fg=#{@dark_gray}"
set -g pane-active-border-style "fg=#{@gray},bold"
set-hook -g window-layout-changed "set-window -F pane-border-status '#{?#{==:#{window_panes},1},off,top}'"

# Options
set -g status off
set -g status-position top
set -g status-justify centre
set -g set-clipboard external
set -g status-interval 5
setw -g aggressive-resize on
set -g focus-events on
set -g display-time 4000
set -g history-limit 50000
set -s escape-time 0
set -g repeat-time 0

# Panes Config
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on
set -g base-index 1
setw -g pane-base-index 1

# Keybinds
unbind C-b
unbind r
unbind "Up"
unbind "Down"
unbind "Left"
unbind "Right"
bind -n C-space set status on \;\
  switch-client -T prefix \;\
  run-shell -d 1 -b "while [ $(tmux display-message -p '##{client_prefix}') -eq 1 ]; do sleep 0.5; done; tmux set status off"
bind C-Space send-prefix
bind R source-file ~/.tmux.conf
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind x kill-pane
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection
bind -T prefix 'h' select-pane -L
bind -T prefix 'j' select-pane -D
bind -T prefix 'k' select-pane -U
bind -T prefix 'l' select-pane -R
bind C-p previous-window
bind C-n next-window

# Terminal fixes
set -g allow-passthrough on
set -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "xterm-kitty"
setw -q -g utf8 on
set -g mouse on
setw -g mode-keys vi

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
