#!/bin/bash

S_MIN=30

BAT=$(ls -d /sys/class/power_supply/BAT* | head -n1)
LAST=""

apply_mode() {
  read -r PCT < "$BAT/capacity"
  read -r STAT < "$BAT/status"

  if [[ -f "$LOCK" ]]; then
    MODE=$(<"$LOCK")
  else
    if [[ "$STAT" == "Charging" || "$STAT" == "Full" ]]; then
      MODE="balanced"
    elif (( PCT < S_MIN )); then
      MODE="power-saving"
    else
      MODE="balanced"
    fi
  fi

  if [[ "$MODE" != "$LAST" ]]; then
    tlpctl "$MODE" 2>/dev/null || tlpctl balanced
    notify-send -r 9991 \
      "Activating Power Mode: $MODE" \
      "Battery: ${PCT}% (${STAT})"

    LAST="$MODE"
  fi
}

apply_mode

udevadm monitor --udev --subsystem-match=power_supply |
  while read -r line; do
    [[ "$line" == *"change"* ]] && apply_mode
  done
