#!/usr/bin/env bash

get_album_art() {
  url=$(playerctl metadata mpris:artUrl)
  if [[ $url == "file://"* ]]; then
    echo "${url/file:\/\//}"
  elif [[ $url == "http://"* ]] || [[ $url == "https://"* ]]; then
    # Identify filename from URL
    filename="$(echo $url | sed "s/.*\///")"

    # Download file to /tmp if it doesn't exist
    if [ ! -f "/tmp/$filename" ]; then
      wget -O "/tmp/$filename" "$url"
    fi

    echo "/tmp/$filename"
  else
    echo ""
  fi
}

get_brightness() {
  local mon="$1"
  if [[ $mon == "0" ]]; then
    declare -i absb
    declare -i relb
    absb=$(brightnessctl g)
    maxb=$(brightnessctl m)
    absb=$(( absb * 100 ))
    echo $(( absb / maxb ))
  else
    cat ~/.cache/mon-brightness
  fi
}

notify-vol() {
  volume=$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $2}')
  volume=$(awk "BEGIN { print $volume * 100 }")
  muted=$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $3}' | tr -d "[]")
  album_art=$(get_album_art)
  current_song=$(playerctl -f "{{title}} - {{artist}}" metadata)

  if [[ "$muted" == "MUTED" ]]; then
    notify-send -t 1500 -h string:x-dunst-stack-tag:volume_notif -h int:value:0 -i "$album_art" "󰖁 Muted" "$current_song"
  else
    notify-send -t 1500 -h string:x-dunst-stack-tag:volume_notif -h int:value:$volume -i "$album_art" "󱄠 $volume%" "$current_song"
  fi

}

notify-brightness() {
  brightness=$(get_brightness "$1")
  notify-send -h string:x-dunst-stack-tag:brightness_notif -h int:value:$brightness "󰃠 $brightness%"
}

main() {
  case "$1" in
    "vol") notify-vol
      ;;
    "brightness") notify-brightness "$2"
      ;;
  esac
}

main "$@"
