#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/Immagini/Wallpapers"
WALLPAPER_SLEEP_TIME=$((60*5))
TIMER_FILE="/tmp/wallpaper_timer"

next(){
  CURRENT_WALL=$(swww query | awk '{ print $8 }' | xargs basename)
  WALLPAPER=$(find "$WALLPAPER_DIR" -type d -name ".git" -prune -o -type f ! -name "$CURRENT_WALL" -print | shuf -n 1)
  if [[ ${WALLPAPER##*.} == "gif" ]]; then
    swww img --fill-color=161616 "${WALLPAPER}"
  else
    swww img --resize=fit --fill-color=161616 "${WALLPAPER}"
  fi
}

get_time(){
  echo $(cat "${TIMER_FILE}")
}

loop(){
  # Infinite loop
  while true; do
    # Check for current wallpaper
    CURRENT_WALL=$(swww query | awk '{ print $8 }' | xargs basename)
    # Get random wallpaper
    WALLPAPER=$(find "$WALLPAPER_DIR" -type d -name ".git" -prune -o -type f ! -name "$CURRENT_WALL" -print | shuf -n 1)
    if [[ ${WALLPAPER##*.} == "gif" ]]; then
      swww img --fill-color=161616 "${WALLPAPER}"
    else
      swww img --resize=fit --fill-color=161616 "${WALLPAPER}"
    fi

    # Inizialize timer
    echo -n "${WALLPAPER_SLEEP_TIME}" > "${TIMER_FILE}"
    while true; do
      timer=$(cat "${TIMER_FILE}")
      if [[ $timer -gt 0 ]]; then
        timer=$(($timer - 1))
        echo -n "$timer" > "${TIMER_FILE}"
        sleep 1;
      else
        break 
      fi
    done
  done
}

main(){
  case $1 in
    "next") next
      ;;
    "time") get_time
      ;;
    "")
      if ! pgrep -f "${0}" | grep -v "${$}" 1>/dev/null; then 
        if [[  -e $TIMER_FILE ]]; then
          rm "$TIMER_FILE"
        fi
        touch "$TIMER_FILE"
        trap "rm -f ${TIMER_FILE}" EXIT
        loop &
      else
        echo "Already in execution"
        exit 1
      fi
      ;;
    *) exit 1
      ;;
  esac
}

main $@
