#!/usr/bin/env bash

if [[ $(pgrep -f wallpaper-daemon | wc -l) -gt 0 ]]; then
  exit 1
fi

# Runtime shared variables
WALLPAPER_FILE=/tmp/wallpaper_file
SLEEP_FILE=/tmp/wallpaper_sleep

# Runtime shared status
TIMER_FILE=/tmp/wallpaper_timer
LOCK_FILE=/tmp/wallpaper_lock

start="false"
timer=0

if [[ -e $WALLPAPER_FILE ]]; then
  rm -f $WALLPAPER_FILE
fi
touch $WALLPAPER_FILE

if [[ -e $SLEEP_FILE ]]; then
  rm -f $SLEEP_FILE
fi
touch $SLEEP_FILE
echo -n 0 > $SLEEP_FILE

if [[ -e $TIMER_FILE ]]; then
  rm -f $TIMER_FILE
fi
touch $TIMER_FILE
echo -n 0 > $TIMER_FILE

if [[ -e $LOCK_FILE ]]; then
  rm -f $LOCK_FILE
fi
touch $LOCK_FILE
echo -n "false" > $LOCK_FILE


get_wallpaper(){
  WALLPAPER_DIR=$(cat $WALLPAPER_FILE)
  CURRENT_WALL=$(swww query | awk '{ print $8 }' | xargs basename)
  WALLPAPER=$(find "$WALLPAPER_DIR" -type d -name ".git" -prune -o -type f ! -name "$CURRENT_WALL" -print | shuf -n 1)
  if [[ ${WALLPAPER##*.} == "gif" ]]; then
    swww img --fill-color=161616 "${WALLPAPER}"
  else
    swww img --resize=fit --fill-color=161616 "${WALLPAPER}"
  fi
}

timer_wait(){
  (
    flock -n 200 || exit 1

    sleep_time=$(cat $SLEEP_FILE)
    echo -n $sleep_time > $TIMER_FILE
    while :; do 
      timer=$(cat $TIMER_FILE)
      if [[ $timer -gt 0 ]]; then
        sleep 1
        timer=$((timer - 1))
        echo -n $timer > $TIMER_FILE
      else
        break
      fi
    done
  )200>$TIMER_FILE
}

daemon() {
  while :; do
    start=$(cat $LOCK_FILE) 
    while [[ $start == "true" ]]; do
      get_wallpaper
      timer_wait
      start=$(cat $LOCK_FILE) 
    done
  done

  rm -f $LOCK_FILE $TIMER_FILE
}

daemon
