#!/usr/bin/env bash

HYPR_ADDR="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
skip=0

if [ ! -S "$HYPR_ADDR" ]; then
  echo "Could not find Hyprland socket. Ensure you are running this inside Hyprland."
  exit 1
fi

echo "Listening for Urgency signals..."

socat -U - "UNIX-CONNECT:$HYPR_ADDR" | while read -r line; do
if [[ "$line" == urgent* ]]; then
  if [[ $skip -eq 0 ]]; then
    skip=1
    continue
  else
    skip=0
    addr="0x${line#*>>}"

    win_info=$(hyprctl clients -j | jq -r ".[] | select(.address == \"$addr\")")

    title=$(echo "$win_info" | jq -r '.title')
    class=$(echo "$win_info" | jq -r '.class')
    workspace=$(echo "$win_info" | jq -r '.workspace.id')

    notify-send -u critical -t 2500 -a "Hyprland" -i "dialog-warning" \
      "🚨 Urgent: $class" \
      "Window: $title\nWorkspace $workspace"

    hyprctl dispatch focuswindow address:"$addr"
  fi
fi
done
