git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  nerdFontsVersion: "3"
  showRandomTip: false
disableStartupPopups: true
notARepository: 'skip'
promptToReturnFromSubprocess: false

