git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
gui:
  nerdFontsVersion: "3"
  showRandomTip: false
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
    rate: 80
disableStartupPopups: true
notARepository: "skip"
promptToReturnFromSubprocess: false
keybinding:
  files:
    commitChangesWithEditor: <disabled>
customCommands:
  - key: "C"
    context: "files"
    description: "Signed Commit"
    prompts:
      - type: "input"
        key: "test"
        title: "Signed Commit"
    command: "git commit -S -m {{.Form.test}}"
    loadingText: "Creating Signed Commit"
