#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Info:
#   author:    Miroslav Vidovic
#   file:      web-search.sh
#   created:   24.02.2017.-08:59:54
#   revision:  ---
#   version:   1.0
# -----------------------------------------------------------------------------
# Requirements:
#   rofi
# Description:
#   Use rofi to search the web.
# Usage:
#   web-search.sh
# -----------------------------------------------------------------------------
# Script:

URL="https://www.google.com/search?q="

main() {
  query=$(rofi -dmenu -matching fuzzy -location 0 -p "   " -theme ~/.config/rofi/launchers/type-1/style-10.rasi)
  if [[ $(echo $query | cut -c 1-3) == "www" ]]; then
		xdg-open "http://$query"
	else
		xdg-open "$URL$query"
  fi
}
main
