### KEYBINDS ###
# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER 														# Sets "Windows" key as main modifier

# Panes control
bind = $mainMod, T, exec, $terminal 							# Terminal [kitty]
bind = $mainMod CONTROL_L, Q, exit 								# Quit hyprland session
bind = $mainMod, Q, killactive 									# Close pane
bind = $mainMod, V, togglefloating 								# Toggle tilting-floating panes
bind = $mainMod, R, exec, $menu 									# Applications menu
bind = $mainMod, P, pseudo, 										# Dinamic size [tilting mode]
bind = $mainMod, J, togglesplit, 								# Change split order [tilting mode]
bind = $mainMod, F, exec, $browser 								# Browser [Firefox]
bind = $mainMod, L, exec, $lock 									# Lock [Swaylock]
bind = $mainMod, left, movefocus, l 							# Move focus left
bind = $mainMod, right, movefocus, r 							# Move focus right
bind = $mainMod, up, movefocus, u 								# Move focus up
bind = $mainMod, down, movefocus, d 							# Move focus down
bindm = $mainMod, mouse:272, movewindow 						# Move pane
bindm = $mainMod, mouse:273, resizewindow 					# Resize pane
bind = , F11, fullscreen 											# Fullscreen
bind = SHIFT, F11, fullscreen, 1									# Monocle window layout
bind = , PRINT, exec, ~/.config/rofi/use/screenshot			# Full screen screenshot
bind = $mainMod, ESCAPE, exec, ~/.config/rofi/use/powermenu # Quit menu
bind = $mainMod SHIFT, W, exec, ~/.config/hypr/scripts/launch-waybar # Reload waybar
bind = $mainMod, A, exec, ~/.config/rofi/use/launcher # Launch apps
bind = $mainMod, RETURN, exec, ~/.config/rofi/use/launcher_full # Launch apps [Fullscreen]
bind = $mainMod CONTROL_L, M, exec, ~/.config/rofi/use/mpd # MPD Control pannel
bind = $mainMod SHIFT, A, exec, ~/.config/rofi/use/apps  # Launch main apps 
bind = $mainMod, SPACE, exec, ulauncher         # Ulauncher

# Workspaces
bind = $mainMod, 1, workspace, 1 								# Workspace 1
bind = $mainMod, 2, workspace, 2 								# Workspace 2
bind = $mainMod, 3, workspace, 3 								# Workspace 3
bind = $mainMod, 4, workspace, 4 								# Workspace 4
bind = $mainMod, 5, workspace, 5 								# Workspace 5
bind = $mainMod, 6, workspace, 6 								# Workspace 6
bind = $mainMod, 7, workspace, 7 								# Workspace 7
bind = $mainMod, 8, workspace, 8 								# Workspace 8
bind = $mainMod, 9, workspace, 9 								# Workspace 9
bind = $mainMod, 0, workspace, 10 								# Workspace 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1					# Move to workspace 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2					# Move to workspace 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3					# Move to workspace 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4					# Move to workspace 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5					# Move to workspace 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6					# Move to workspace 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7					# Move to workspace 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8					# Move to workspace 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9					# Move to workspace 9
bind = $mainMod SHIFT, 0, movetoworkspace, 1					# Move to workspace 10

bind = $mainMod, S, togglespecialworkspace, magic 			# Special workspace [magic]
bind = $mainMod SHIFT, S, movetoworkspace, special:magic # Move to special workspace [magic]
bind = $mainMod, M, togglespecialworkspace, sfx 			# Special workspace [sfx]
bind = $mainMod SHIFT, M, movetoworkspace, special:sfx 	# Move to special workspace [sfx]

# Utility
bind = Control_L, up, exec, $vol_up 							# Increase volume
bind = Control_L, down, exec, $vol_down 						# Decrease volume
bind = Control_L, right, exec, $vol_mute 						# Mute volume
