# hyprland @ environment
# Wiki: https://wiki.hypr.land/Configuring/Environment-variables

# Using uwsm! See ~/.config/uwsm/env and env-hyprland

$terminal = kitty
$fileManager = kitty -e spf
$taskManager = kitty -e btop
$menu = vicinae
$browser = firefox
$zed = zeditor
$waybar = $HOME/.config/hypr/scripts/start-waybar horizzontal
