# hyprland @ autostart

exec-once = swww-daemon & "$HOME/.config/hypr/scripts/wallpaper.sh" 
exec-once = waybar
exec = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
exec-once = vicinae server

