# hyprland @ environment
# Wiki: https://wiki.hypr.land/Configuring/Environment-variables

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps
env = GDK_SCALE,2
env = XCURSOR_SIZE,32

$terminal = kitty
$fileManager = kitty -e spf
$taskManager = kitty -e btop
$menu = vicinae
$browser = firefox
$zed = zeditor
