$foreground = #CDD6F4

# BACKGROUND
background {
  monitor =
  path = screenshot
  # path = /tmp/wallpaper-current
  #color = $background
  blur_passes = 2
  blur_size = 4
  contrast = 1
  brightness = 0.5
  vibrancy = 0.2
  vibrancy_darkness = 0.2
}

# GENERAL
general {
  hide_cursor = false
}

# INPUT FIELD
input-field {
  monitor =
  size = 250, 60
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.35
  dots_center = true
  outer_color = rgba(205, 214, 244, 0.25)
  inner_color = rgba(30, 30, 46, 0.45)
  font_color = rgb(205, 214, 244)
  check_color = rgb(166, 227, 161)
  fail_color = rgb(243, 139, 168)
  fade_on_empty = false
  hide_input = false
  rounding = 30
  placeholder_text = Input Password...
  position = 0, -200
  halign = center
  valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] date +"%A, %B %d"
  color = rgba(242, 243, 244, 0.75)
  font_size = 22
  font_family = JetBrains Mono Nerd Font
  position = 0, 300
  halign = center
  valign = center
  shadow_passes = 2
  shadow_size = 3
}

# TIME
label {
  monitor =
  text = cmd[update:1000] date +"%-I:%M"
  color = rgba(242, 243, 244, 0.75)
  font_size = 95
  font_family = JetBrains Mono Extrabold
  position = 0, 200
  halign = center
  valign = center
  shadow_passes = 2
  shadow_size = 3
}



# Profile Picture
image {
  monitor =
  path = /home/Nias/Documenti/Profile_Picture.jpg
  size = 100
  border_size = 2
  border_color = $foreground
  position = 0, -100
  halign = center
  valign = center
}

# MUSIC
label {
  monitor =
  text = cmd[update:1000] ~/.config/hypr/scripts/music.sh
  color = rgba(242, 243, 244, 0.75)
  font_size = 18
  font_family = JetBrains Mono Nerd Font Mono
  position = 0, 50
  halign = center
  valign = bottom
}

# USER
label {
  monitor =
  text = cmd[update:5000] ~/.config/hypr/scripts/whoami.sh
  color = rgba(242, 243, 244, 0.75)
  font_size = 16
  font_family = JetBrains Mono Nerd Font Mono
  position = 0, -10
  halign = center
  valign = top
}

# NETWORK
label {
  monitor =
  text = cmd[update:10000] ~/.config/hypr/scripts/network.sh
  color = rgba(242, 243, 244, 0.75)
  font_size = 20
  font_family = JetBrains Mono Nerd Font Mono
  position = 40, -10
  halign = left
  valign = top
}

# BATTERY
label {
  monitor =
  text = cmd[update:30000] ~/.config/hypr/scripts/battery.sh
  color = rgba(242, 243, 244, 0.75)
  font_size = 18
  font_family = JetBrains Mono Nerd Font Mono
  position = -40, -10
  halign = right
  valign = top
}

# background {
#   monitor =
#     path = /tmp/wallpaper_current
#     blur_size = 3
#     blur_passes = 3
#     noise = 0
#     reload_time = 60
# }
