# hyprland @ windowrules
# Wiki: https://wiki.hypr.land/Configuring/Window-Rules - https://wiki.hypr.land/Configuring/Workspace-Rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Floating rule for xdg popups
windowrule = float, class:(X|x)dg-desktop-portal.*
windowrule = float, class:zenity
windowrule = float, class:firefox, title:(Libreria)
windowrule = float, class:org.prismlauncher.PrismLauncher, title:^(.*console.*)
windowrule = float, class:org.mozilla.Thunderbird, title:^(.*Reminders)

# Disable gaps in fullscreen
workspace = f[1], gapsout:0, gapsin:0

# Set xdg-portal popup size
windowrulev2 = size 700 500, class:((X|x)dg-desktop-portal.*)
windowrulev2 = size 1036 508, class:gimp, title:(Apri immagine)

# Set transparent windows
windowrulev2 = noblur, xwayland:1, floating:1
windowrulev2 = opacity 0.8, class:^(com.github.th_ch.youtube_music|steam|jetbrains-idea-ce|dev.zed.Zed|discord)$
windowrulev2 = opacity 0.8, title:^(superfile)$
windowrulev2 = opacity 0.9, class:^(jetbrains-idea-ce)$
