### ENVIRONMENT ###
# See https://wiki.hyprland.org/Configuring/Environment-variables/

# Globals
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# qt6
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_STYLE_OVERRIDE,kvantum 

# Locals
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$browser = firefox
$notion = notion-app
$vol_up = ~/.config/hypr/scripts/volume 5%+
$vol_down = ~/.config/hypr/scripts/volume 5%-
$vol_mute =  ~/.config/hypr/scripts/volume toggle-mute
$lock = ~/.config/hypr/scripts/lock



