# hyprland @ autostart

exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"   # for GTK3 apps
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

exec-once = uwsm app -- swww-daemon 
exec-once = uwsm app -- mako
exec-once = uwsm app -- vicinae server
exec-once = uwsm app -- mpDris2 -j
exec-once = uwsm app -- $HOME/.config/hypr/scripts/wallpaper
exec-once = uwsm app -- $HOME/.config/hypr/scripts/keepassxc-unlock

exec-once = $waybar
