# hyprland @ windowrules
# Wiki: https://wiki.hypr.land/Configuring/Window-Rules - https://wiki.hypr.land/Configuring/Workspace-Rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus 1

# Set transparent windows
windowrule = match:xwayland true, match:float true, no_blur true
windowrule = match:class ^(com.github.th_ch.youtube_music|steam|dev.zed.Zed|discord|org.gnome.Calculator)$, opacity 0.8 override,
windowrule = match:title ^(superfile)$, opacity 0.8 override
windowrule = match:class ^(jetbrains-idea)$, opacity 0.9 override
windowrule = match:class ^(gimp)$, opacity 1.0 1.0 override, no_blur true

# Floating rules
windowrule = match:float true, match:xwayland false, center true
windowrule = match:float true, match:xwayland true, opacity 1.0 override

windowrule = match:class ^((X|x)dg-desktop-portal.*)$, float true, size 700 500
windowrule = match:class ^(zenity|qemu)$
windowrule = match:class ^(librewolf)$, match:title ^(Library)$
windowrule = match:class ^(org.prismlauncher.PrismLauncher)$, match:title ^(.*console.*)$
windowrule = match:class ^(org.mozilla.Thunderbird)$, match:title ^(.*Reminders)$
windowrule = match:class ^(gimp|file-jpeg)$, match:title (Apri.*|Esporta.*), size 1036 508
