# hyprland @ windowrules
# Wiki: https://wiki.hypr.land/Configuring/Window-Rules - https://wiki.hypr.land/Configuring/Workspace-Rules

# Smart Gaps
workspace = w[tv1], gapsout:1, gapsin:0
workspace = f[1], gapsout:1, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]

windowrule {
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}

windowrule {
  name = Floating-xdg-portals
  match:class = ^(X|x)dg-desktop-portal.*

  float = true
}

windowrule {
  name = floating-windows-size-position
  match:float = true
  match:xwayland = false

  # size = 700 500
  center = true
}

windowrule {
  name = fix-xwayland-drags
  match:class = .*
  match:title = .*
  match:xwayland = true
  match:float = true

  no_initial_focus = true
  no_anim = true
}

windowrule {
  name = fix-xwayland-blur
  match:float = true
  match:xwayland = true

  opacity = 1.0 override
  no_blur = true
}

# Opacity
windowrule = match:class ^(dev.zed.Zed|jetbrains-idea|com.github.th_ch.youtube_music)$, opacity 0.9 override
windowrule = match:title ^(superfile)$, opacity 0.8 override
windowrule = match:class ^(gimp)$, opacity 1.0 override 1.0 override 1.0 override, no_blur true

# Floating
windowrule = match:class ^(file-jpeg)$, float true
windowrule = match:class ^(steam)$, match:title ^(steam)?.*, float true
windowrule = match:class ^(org.gnome.Calculator)$, size 496 616, float true
