source = ~/.config/hypr/hyprenv.conf
source = ~/.config/hypr/hyprstart.conf
# source = ~/.config/hypr/hyprsettings.conf
source = ~/.config/hypr/hyprsettings_vertical.conf
source = ~/.config/hypr/hyprbinds.conf
source = ~/.config/hypr/hyprrules.conf
