# hyprland @ autostart
exec-once = uwsm app -- udiskie -s
exec-once = uwsm app -- swww-daemon
exec-once = uwsm app -- mako
exec-once = uwsm app -- vicinae server
exec-once = uwsm app -- mpDris2 -j
exec-once = uwsm app -- $HOME/.config/hypr/scripts/workspace-watcher

exec-once = uwsm app -- $waybar
# exec-once = uwsm app -- $HOME/.config/hypr/scripts/waybar_auto_hide --side left &
exec-once = uwsm app -- $HOME/.config/hypr/scripts/wallpaper-daemon
