# hyprland @ Keybinds
# Wiki: https://wiki.hypr.land/Configuring/Binds - https://wiki.hypr.land/Configuring/Keywords

bind = SUPER SHIFT, Return, exec, $terminal
bind = SUPER, Return, exec, $terminal
bind = SUPER, Q, killactive,
bind = SUPER, E, exec, $fileManager
bind = SUPER, V, togglefloating,
bind = SUPER, R, exec, $menu
bind = SUPER SHIFT, R, exec, $menu
bind = SUPER, P, pin, activefocus
bind = SUPER, K, layoutmsg, togglesplit
bind = SUPER, J, layoutmsg, swapsplit
bind = SUPER, F, exec, $browser
bind = SUPER, Z, exec, env $zed
bind = SUPER SHIFT, c, exec, hyprpicker | xargs wl-copy
bind = SUPER, X,  exec, $taskManager
bind = SUPER, SPACE, exec, hyprctl switchxkblayout all next && notify-send "Switched Layout:" "$(hyprctl devices -j | jq -r '.keyboards[] | .active_keymap' | head -n1 | cut -c1-2 | tr 'A-Z' 'a-z')" -t 1000
# bind = , XF86SelectiveScreenshot, exec, grim -g "$(slurp -w 0)" | wl-copy && notify-send "Screenshot saved" -t 2000
# bind = , PRINT, exec, grim | wl-copy && notify-send "Screenshot saved" -t 2000
bind = , F11, fullscreen

# Window movement/management
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10
bind = SUPER, S, togglespecialworkspace, magic

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10
bind = SUPER SHIFT, S, movetoworkspace, special:magic

# Cycle focus
binde = SUPER, Tab, cyclenext
bind = SUPER, Tab, alterzorder, top

binde = SUPER SHIFT, Tab, cyclenext, prev
bind = SUPER SHIFT, Tab, alterzorder, top

bind = SUPER CTRL, H, movefocus, l
bind = SUPER CTRL, H, alterzorder, top
bind = SUPER CTRL, L, movefocus, r
bind = SUPER CTRL, L, alterzorder, top
bind = SUPER CTRL, K, movefocus, u
bind = SUPER CTRL, K, alterzorder, top
bind = SUPER CTRL, J, movefocus, d
bind = SUPER CTRL, J, alterzorder, top

# Resizing
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

binde = SUPER SHIFT, L, resizeactive, 30 0
binde = SUPER SHIFT, H, resizeactive, -30 0

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && $notify vol
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && $notify vol
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && $notify vol
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+ && $notify brightness
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%- && $notify brightness
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
# bind = ,XF86Display, dpms, toggle # blind yourself
bind = ,XF86Display, exec, dpms-off # blind yourself
